language: minimal

services:
- docker

before_install:
- docker build -t scheme_x86_travis -f Dockerfile.travis .

script:
- docker run -it -v $(pwd):/code scheme_x86_travis:latest /bin/bash -c 'cd /code/src/ && make test'
